apiVersion: v1
kind: ConfigMap
metadata:
  name: amqp-gateway-configmap
  namespace: argo-events
data:
  amqp.fooConfig: |-
    url: amqp://amqp.argo-events:5672
    attributes:
      exchangeName: fooExchangeName
      exchangeType: fanout
      routingKey: fooRoutingKey
  amqp.barConfig: |-
    url: amqp://amqp.argo-events:5672
    attributes:
      exchangeName: barExchangeName
      exchangeType: fanout
      routingKey: barRoutingKey
