apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-gateway-configmap
data:
  input: |-
    s3EventConfig:
      bucket: input
      endpoint: minio-service.argo-events:9000
      event: s3:ObjectCreated:Put
      filter:
        prefix: ""
        suffix: ""
    insecure: true
    accessKey:
      key: accesskey
      name: artifacts-minio
    secretKey:
      key: secretkey
      name: artifacts-minio
  output: |-
    s3EventConfig:
      bucket: output
      endpoint: minio-service.argo-events:9000
      event: s3:ObjectCreated:Put
      filter:
        prefix: ""
        suffix: ""
    insecure: true
    accessKey:
      key: accesskey
      name: artifacts-minio
    secretKey:
      key: secretkey
      name: artifacts-minio
