language: go
go:
  - 1.x

services:
  - docker

cache:
  directories:
    - $HOME/bin

env:
  global:
    - PATH=$HOME/bin:$PATH

before_install:
  - go get github.com/mattn/goveralls
  - go get sigs.k8s.io/kind
  - if [ ! -d $HOME/bin/kubectl ]; then
      mkdir -p $HOME/bin;
      curl -o $HOME/bin/kubectl -L https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubectl;
      chmod +x $HOME/bin/kubectl;
    fi

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep version
  - dep ensure -vendor-only

script:
  - make all
  - make test coverage
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - make build-e2e-images
  - make kind-e2e

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
