language: go
go:
  - "1.13"

services:
  - docker

cache:
  directories:
    - $HOME/bin
    - $HOME/docker

env:
  global:
    - DOCKER_PUSH=false
    - PATH=$HOME/bin:$PATH

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - go get github.com/mattn/goveralls
  - if [ ! -d $HOME/bin/kubectl ]; then
    mkdir -p $HOME/bin;
    curl -o $HOME/bin/kubectl -L https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubectl;
    chmod +x $HOME/bin/kubectl;
    fi

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

script:
  - make test
  - make all
  - make test coverage
