required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/code-generator/cmd/go-to-protobuf",
  "k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo",
  "k8s.io/gengo/examples/deepcopy-gen",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gogo/protobuf/protoc-gen-gofast",
  "github.com/gogo/protobuf/protoc-gen-gogofast",
  "gopkg.in/src-d/go-git.v4"
]

[[constraint]]
  name = "github.com/adlio/trello"
  branch = "master"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.10"

[[constraint]]
  name = "github.com/nats-io/go-nats-streaming"
  branch = "master"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  branch = "master"

[[constraint]]
  name = "github.com/nlopes/slack"
  branch = "master"

[[constraint]]
  name = "cloud.google.com/go"
  branch = "master"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.17.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[[constraint]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.5.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  name = "github.com/streadway/amqp"
  branch = "master"

[[constraint]]
  name = "github.com/argoproj/argo"
  version = "v2.2.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "v1.20.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  branch = "master"

[[constraint]]
  name = "github.com/Knetic/govaluate"
  branch = "master"

[[constraint]]
  name = "github.com/colinmarc/hdfs"
  revision = "48eb8d6c34a97ffc73b406356f0f2e1c569b42a5"

[[constraint]]
  name = "gopkg.in/jcmturner/gokrb5.v5"
  version = "5.3.0"

[[override]]
  branch = "release-1.14"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.14"
  name = "k8s.io/apimachinery"

[[override]]
  branch = "release-11.0"
  name = "k8s.io/client-go"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false

[[constraint]]
  name = "github.com/google/go-github"
  revision = "50be09d24ee31a2b0868265e76c24b9545a6eb7a"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "b90029ef6cd877cb3f422d75b3a07707e3aac6b7"
