required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/code-generator/cmd/go-to-protobuf",
  "k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gogo/protobuf/protoc-gen-gofast",
  "github.com/gogo/protobuf/protoc-gen-gogofast",
  "github.com/micro/protoc-gen-micro",
]

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.10"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.5.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  name = "github.com/streadway/amqp"
  branch = "master"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "github.com/argoproj/argo"
  version = "v2.1.0-beta2"

[[constraint]]
  name = "github.com/nats-io/gnatsd"
  version = "1.1.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.16.0"

[[override]]
  branch = "release-1.10"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[override]]
  branch = "release-7.0"
  name = "k8s.io/client-go"

[[override]]
  name = "github.com/micro/go-plugins"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
