site_name: Argo Events - The Event-Based Dependency Manager for Kubernetes
repo_url: https://github.com/argoproj/argo-events
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
google_analytics:
  - 'UA-105170809-2'
  - 'auto'
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: 'index.md'
  - Installation:
      - 'installation.md'
      - 'managed-namespace.md'
      - 'validating-admission-webhook.md'
  - 'quick_start.md'
  - Concepts:
      - 'concepts/architecture.md'
      - 'concepts/event_source.md'
      - 'concepts/sensor.md'
      - 'concepts/eventbus.md'
      - 'concepts/trigger.md'
  - Tutorials:
      - 'tutorials/01-introduction.md'
      - 'tutorials/02-parameterization.md'
      - 'tutorials/03-trigger-sources.md'
      - 'tutorials/04-standard-k8s-resources.md'
      - 'tutorials/05-trigger-custom-resources.md'
      - 'tutorials/06-trigger-conditions.md'
      - 'tutorials/07-filters.md'
      - 'tutorials/08-policy.md'
  - EventSources:
      - Setup:
          - 'eventsources/setup/amqp.md'
          - 'eventsources/setup/aws-sns.md'
          - 'eventsources/setup/aws-sqs.md'
          - 'eventsources/setup/calendar.md'
          - 'eventsources/setup/emitter.md'
          - 'eventsources/setup/file.md'
          - 'eventsources/setup/gcp-pub-sub.md'
          - 'eventsources/setup/github.md'
          - 'eventsources/setup/gitlab.md'
          - 'eventsources/setup/kafka.md'
          - 'eventsources/setup/minio.md'
          - 'eventsources/setup/mqtt.md'
          - 'eventsources/setup/nats.md'
          - 'eventsources/setup/nsq.md'
          - 'eventsources/setup/redis.md'
          - 'eventsources/setup/resource.md'
          - 'eventsources/setup/webhook.md'
          - 'eventsources/setup/pulsar.md'
      - 'eventsources/deployment-strategies.md'
      - 'eventsources/multiple-events.md'
      - 'eventsources/naming.md'
      - 'eventsources/services.md'
      - 'eventsources/webhook-authentication.md'
      - 'eventsources/webhook-health-check.md'
      - 'eventsources/calendar-catch-up.md'
      - 'eventsources/gcp-pubsub.md'
      - 'eventsources/generic.md'
  - Sensors:
      - Triggers:
          - 'triggers/argo-workflow.md'
          - 'triggers/aws-lambda.md'
          - 'triggers/http-trigger.md'
          - 'triggers/nats-trigger.md'
          - 'triggers/kafka-trigger.md'
          - 'triggers/k8s-object-trigger.md'
          - 'triggers/log.md'
          - 'triggers/openwhisk-trigger.md'
          - 'triggers/slack-trigger.md'
          - 'triggers/build-your-own-trigger.md'
      - 'trigger-conditions.md'
      - More Information: 'more-about-sensors-and-triggers.md'
  - 'eventbus.md'
  - 'service-accounts.md'
  - Operator Guide:
      - 'metrics.md'
      - HA/DR Recommendations: 'dr_ha_recommendations.md'
  - 'developer_guide.md'
  - 'FAQ.md'
  - Releases ⧉: 'releases.md'
  - Roadmap ⧉: https://github.com/argoproj/argo-events/milestones
  - Blog ⧉: https://blog.argoproj.io/
