site_name: Argo Events - The Event-Based Dependency Manager for Kubernetes
repo_url: https://github.com/argoproj/argo-events
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
google_analytics:
  - 'UA-105170809-2'
  - 'auto'
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: 'index.md'
  - 'installation.md'
  - 'quick_start.md'
  - Concepts:
      - 'concepts/gateway.md'
      - 'concepts/sensor.md'
      - 'concepts/event_source.md'
      - 'concepts/trigger.md'
      - 'concepts/architecture.md'
  - Demo:
      - 'demo/notebooks.md'
  - Setup:
      - 'setup/amqp.md'
      - 'setup/aws-sns.md'
      - 'setup/aws-sqs.md'
      - 'setup/calendar.md'
      - 'setup/emitter.md'
      - 'setup/file.md'
      - 'setup/gcp-pub-sub.md'
      - 'setup/github.md'
      - 'setup/gitlab.md'
      - 'setup/kafka.md'
      - 'setup/minio.md'
      - 'setup/mqtt.md'
      - 'setup/nats.md'
      - 'setup/nsq.md'
      - 'setup/redis.md'
      - 'setup/resource.md'
      - 'setup/webhook.md'
  - Tutorials:
      - 'tutorials/01-introduction.md'
      - 'tutorials/02-parameterization.md'
      - 'tutorials/03-trigger-sources.md'
      - 'tutorials/04-standard-k8s-resources.md'
      - 'tutorials/05-trigger-custom-resources.md'
      - 'tutorials/06-circuit-and-switch.md'
      - 'tutorials/07-filters.md'
      - 'tutorials/08-policy.md'
      - 'tutorials/09-events-over-nats.md'
  - Triggers:
      - 'triggers/argo-workflow.md'
      - 'triggers/aws-lambda.md'
      - 'triggers/http-trigger.md'
      - 'triggers/nats-trigger.md'
      - 'triggers/kafka-trigger.md'
      - 'triggers/k8s-object-trigger.md'
      - 'triggers/openwhisk-trigger.md'
  - 'developer_guide.md'
  - 'controllers.md'
  - 'FAQ.md'
  - Releases ⧉: https://github.com/argoproj/argo-events/releases
  - Roadmap ⧉: https://github.com/argoproj/argo-events/milestones
  - Blog ⧉: https://blog.argoproj.io/
