apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  - rbac

patchesJson6902:
  - path: ./overlays/gateway-controller-configmap.yaml
    target:
      group: ""
      kind: ConfigMap
      name: gateway-controller-configmap
      version: v1
  - path: ./overlays/sensor-controller-configmap.yaml
    target:
      group: ""
      kind: ConfigMap
      name: sensor-controller-configmap
      version: v1
