# For more information, https://github.com/argoproj/argo-events/blob/e0242e7b00f7edc7e0cff314abd3a728ddf3c62b/gateways/core/resource/config.go#L34
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-gateway-event-source
data:
  workflow-success: |-
    namespace: argo-events
    group: "argoproj.io"
    version: "v1alpha1"
    kind: "Workflow"
    type: ADDED
    filter:
      labels:
        workflows.argoproj.io/phase: Succeeded
        name: "my-workflow"
  namespace: |-
    namespace: argo-events
    group: "k8s.io"
    version: "v1"
    kind: "Namespace"
