apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-gateway-event-source
data:
  foo: |-
    port: "12000"
    endpoint: "/foo"
    method: "POST"
    # serverCertPath refers to file where certificate is stored
    serverCertPath: "/etc/secret-volume/cert"
    # serverKeyPath refers to file where private key is stored
    serverKeyPath: "/etc/secret-volume/key"
